server:
  address: 127.0.0.1
  port: 8088

mybatis:
  mapper-locations: classpath:sqlmapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql